server:
  port: 8020
  servlet:
    context-path: '/api/v1'
spring:
  application:
    name: "pruebaT"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "00000"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
